locustempus/main/auth.py
locustempus/main/tests/test_auth.py
locustempus/settings_shared.py

This commit copies over course mapping functionality from Mediathread.

Implement Course mapping

---

locustempus/main/views.py
locustempus/templates/base.html
locustempus/templates/lti_provider/fail_course_configuration.html
locustempus/templates/main/notify_lti_course_connect.txt

Also updates templates to render the pages with styles inside Canvas

Refactor LTI Course Create View

---

cypress/support/commands.js
cypress/support/index.js
locustempus/urls.py

This was not working with SQLite on Jenkins. This removes the route
until we setup a Postgres testing instance.

Removes the reset endpoint

---

media/build/main.css
media/src/project/layer.tsx
media/src/project/project-map-sidebar.tsx
media/src/project/project-map.tsx
media/src/scss/pages/course_project.scss
tsconfig.json

This is sort of a WIP PR. It implements the ability to click on the map and create a new event associated with a particular layer. It also breaks up the project interface components into separate files. 
Later work will introduce the API and refactor the data structure used to hold events.
TL;DR: the architecture is still in-progress

Implement event markers

---

locustempus/settings_shared.py
requirements.txt

Stealing some code from Footprints to make this go

More Spatialite Configuration

---

locustempus/design/__init__.py
locustempus/design/apps.py
locustempus/design/tests.py
locustempus/design/views.py
locustempus/settings_shared.py
locustempus/templates/design/colors.html
locustempus/templates/design/components.html
locustempus/templates/design/identity.html
locustempus/templates/design/index.html
locustempus/templates/design/typography.html
locustempus/urls.py

This commit creates a new Django app to hold design system documentation

Implement Design System app

---

locustempus/main/serializers.py
locustempus/main/tests/test_views_activity.py
locustempus/main/viewsets.py
locustempus/urls.py
media/src/project/project-map-pane-panels.tsx
media/src/project/project-map-pane.tsx
media/src/project/project-map.tsx

This PR sets up an endpoint for the Activity. It also implements a way for Projects to show the instructions of an activity to an author.

Display activity

---

package-lock.json
package.json

Noting this issue:
https://github.com/FortAwesome/Font-Awesome/issues/16592

Update Fontawesome deps

---

locustempus/main/views.py
locustempus/templates/main/activity_detail.html
media/src/activity.tsx
media/src/activity/activity-map.tsx
media/src/activity/layer.tsx
media/src/activity/project-map-pane-panels.tsx
media/src/activity/project-map-pane.tsx
media/src/project-activity-components/overflow-menu.tsx
webpack.common.js

Sets up the 'Activity' React app, taken from the Project app.

Activity setup

---

media/src/activity/activity-map.tsx
media/src/activity/project-map-pane-panels.tsx
media/src/activity/project-map-pane.tsx
media/src/project-activity-components/layers/layer-set.tsx
media/src/project-activity-components/layers/layer.tsx
webpack.prod.js

This PR implements a LayerSet component, for reuse around the application.

Implement new LayerSet component

---

media/src/activity/activity-map.tsx
media/src/project-activity-components/loading-modal.tsx
media/src/project/project-map.tsx
media/src/scss/ltdc-kitchensink/_index.scss
media/src/scss/ltdc-kitchensink/_loading-modal.scss
package-lock.json

Implemets a loading modal to block interaction until the map loads

Loading Indicator: LT-176

---

requirements.txt

Reverts ccnmtl/locustempus#828

Revert "Bump importlib-metadata from 2.1.0 to 2.1.1"

---

package-lock.json
package.json

Reverts ccnmtl/locustempus#824

Revert "Bump webpack from 5.4.0 to 5.9.0"

---

requirements.txt

Downgrade cryptography

---

requirements.txt

Reverts ccnmtl/locustempus#880

Revert "Bump cryptography from 3.2.1 to 3.3.1"

---

media/src/project/project-map-pane.tsx
media/src/scss/ltdc-pane/_map-pane.scss

Panes are responsive. Note that the panes don't slide in/out yet, that will require some React script. The placeholder for the button is in place.

Responsive panes

---

locustempus/main/views.py
media/src/project-activity-components/panels/event-detail-panel.tsx

- Bugfix: incorrect permissions mixin for S3Sign view
- Bugfix: Image source field referenced image caption

Image Upload Permissions Bug

---

media/src/activity/activity-map-pane.tsx
media/src/project-activity-components/layers/layer.tsx
media/src/project-activity-components/overflow-menu.tsx
media/src/project-activity-components/panels/activity.tsx
media/src/project-activity-components/panels/event-detail-panel.tsx
media/src/project/project-map-pane.tsx

- Refactor overflow element, add click handler to close
- Add click event handler to layer menu

Overflow menu and click handling

---

locustempus/main/views.py

I want to consolidate the breadcrumb wayfinder, and roster pages need to have some page_type. I was being adventurous, please see if I'm doing that right.

Add page_type = roster to CourseRosterView and CourseRosterInviteUser

---

media/src/activity/activity-map.tsx
media/src/project/project-map.tsx

- Fix layer visibility bug in Projects
- Fix layer visibility bug for response layers

Layer Visibility bug fixes

---

media/src/activity/activity-map-pane.tsx
media/src/activity/activity-map.tsx
media/src/project-activity-components/panels/event-add-panel.tsx
media/src/project-activity-components/panels/event-edit-panel.tsx
media/src/project/project-map-pane.tsx
media/src/project/project-map.tsx
media/src/utils.ts

- Implement zoom map to fit markers functionality, Project space
- Refactor and implement zoom to extent for the Activity space

Zoom to extent feature

---

locustempus/templates/lti_provider/landing_page.html

(Please excuse the inline styling)

Rudimentary LTI Landing Page

---

locustempus/main/views.py
media/src/project-activity-components/panels/project-create-edit-panel.tsx
media/src/project/project-map-pane.tsx
media/src/project/project-map.tsx

- LT-274 Update project creation flow
- Fix base map bug on project edit
- Flake8

update project creation flow

---

locustempus/main/permissions.py
locustempus/main/serializers.py
locustempus/main/tests/test_permissions.py
media/src/activity/activity-map-pane-panels.tsx
media/src/activity/activity-map.tsx

This commit fixes bugs involving permissions for feedback. It also
scraps using querystring params, which in hindsight, I have no idea what
I was thinking.

Fix Feedback bugs

---

locustempus/main/views.py
locustempus/templates/lti_provider/fail_course_configuration.html

* Handle sandbox courses correctly
* Add CSRF token to the course creation post form

Fix LTI flow

---

locustempus/templates/main/index.html
media/src/scss/ltdc-base/_section.scss
media/src/scss/ltdc-button/_button.scss
media/src/scss/ltdc-typography/_typography.scss

Styling will be added as I do the theme and color work next week.

sign-up, sign-in, and your-workspaces links to the banner section for prominence

---

media/src/project-activity-components/layers/layer.tsx
media/src/scss/ltdc-button/_button.scss
media/src/scss/ltdc-theme/_comm.scss

Styled the prompt-tip-banner for empty layers for prominence

---

cypress/integration/sign-in.spec.js
cypress/integration/sign-up.spec.js
locustempus/templates/base.html
locustempus/templates/django_registration/activate.html
locustempus/templates/django_registration/activation_complete.html
locustempus/templates/django_registration/activation_failed.html
locustempus/templates/django_registration/registration_complete.html
locustempus/templates/django_registration/registration_form.html
locustempus/templates/main/index.html
locustempus/templates/registration/login.html

* Add the cypress test files
* Add data-cy selectors for referenced fields
* Fix: Remove the &mdash; from all the registration templates
* Fix: Add the cu privacy notice

Add sign in & sign up integration tests

---

locustempus/templates/base.html

Link to the search page as it is the most useful.

Hook up impersonate

---

locustempus/templates/main/course_detail.html
media/src/project-activity-components/layers/layer.tsx
media/src/project-activity-components/panels/project-create-edit-panel.tsx
media/src/project/project-map-pane-panels.tsx
media/src/project/project-map.tsx
media/src/scss/ltdc-pages/course_project.scss
media/src/scss/ltdc-pane/_map-pane.scss
media/src/scss/ltdc-theme/_comm.scss

I'm using what [map-gl recommends](https://visgl.github.io/react-map-gl/docs/api-reference/navigation-control) in `project-map.tsx` instead of CSS. Can you check to see if I'm doing it right?

Map padding bugfix, and pane tabs bottom border

---

media/src/activity/activity-map-pane.tsx
media/src/activity/activity-map.tsx
media/src/project-activity-components/panels/event-add-panel.tsx
media/src/project/project-map-pane.tsx
media/src/project/project-map.tsx

- Add layer name to event creation form
- Return to layer view after event creation
- Add layer title to event creation in activity space

Create Event flow updates

---

media/src/activity/activity-map-pane.tsx
media/src/activity/activity-map.tsx
media/src/project-activity-components/common.tsx
media/src/project-activity-components/layers/layer-set.tsx
media/src/project-activity-components/layers/layer.tsx
media/src/project-activity-components/panels/event-detail-panel.tsx
media/src/project-activity-components/panels/event-edit-panel.tsx
media/src/project/project-map-pane.tsx
media/src/project/project-map.tsx

- Implement event detail flow improvements
- Add layer name to event detail pane
- When clicking on an event pin, switch to the layers pane panel
- Update header on event edit, return to previous pane on save
- Prevent users from creating or selecting an event while editing

Event detail and edit flow improvements

---

locustempus/main/models.py
locustempus/main/serializers.py
media/src/activity/activity-map-pane-panels.tsx
media/src/activity/activity-map.tsx

Added formatted submitted and modified dates in model so they can be displayed properly on the Activity panes

Date (submitted, modified) formatting for display

---

locustempus/main/models.py
locustempus/main/serializers.py
media/src/activity/activity-map-pane-panels.tsx
media/src/activity/activity-map.tsx
media/src/utils.ts
requirements.txt

- LT-319 Add submit and modified times to Author response
- LT-320 Add Feedback info to contributor's view
- LT-321 Add response times for contributor

Response and Feedback dates

---

locustempus/main/models.py
locustempus/main/serializers.py
locustempus/main/tests/test_viewsets.py
media/src/activity/activity-map-pane-panels.tsx
media/src/activity/activity-map-pane.tsx
media/src/activity/activity-map.tsx
media/src/project-activity-components/common.tsx
media/src/project-activity-components/layers/layer.tsx
media/src/project-activity-components/notification.tsx
media/src/project/project-map.tsx

- Implement by-line
- LT-330 Add truncated text to map popups

front end adjustments

---

media/src/activity/activity-map-pane-panels.tsx
media/src/project-activity-components/panels/activity.tsx
media/src/project-activity-components/panels/event-add-panel.tsx
media/src/project-activity-components/panels/event-edit-panel.tsx
media/src/project-activity-components/panels/project-create-edit-panel.tsx
media/src/scss/ltdc-base/_section.scss
media/src/scss/ltdc-list/_menu.scss
media/src/scss/ltdc-pane/_map-pane.scss
media/src/scss/ltdc-theme/_comm.scss
media/src/scss/ltdc-typography/_typography.scss

If you don't mind, can you merge this before the QA at 9:45AM on Tuesday? Thank you!

Activity-response UI and UX

---

cypress/integration/workspace.spec.js
locustempus/main/forms.py
locustempus/main/models.py
locustempus/main/templatetags/course_tools.py
locustempus/main/tests/factories.py
locustempus/main/tests/test_forms.py
locustempus/main/tests/test_permissions.py
locustempus/main/tests/test_views_course.py
locustempus/main/views.py
locustempus/templates/main/course_create.html
locustempus/templates/main/course_detail.html
locustempus/templates/main/course_edit.html
locustempus/templates/main/course_list.html

- Implement Course description field, custom template tags
- Implement Activity status annotation

template context additions

---

locustempus/settings_shared.py

More work needs to be done on the permissions front. Until that happens, obscure the interface.

Remove the browseable api

---

locustempus/templates/base.html
media/src/activity/activity-map-pane-panels.tsx
media/src/project-activity-components/panels/event-add-panel.tsx
media/src/project-activity-components/panels/event-detail-panel.tsx
media/src/project-activity-components/panels/event-edit-panel.tsx
media/src/project-activity-components/panels/project-create-edit-panel.tsx
media/src/scss/ltdc-button/_button.scss
media/src/scss/ltdc-kitchensink/_skip-header.scss
media/src/scss/ltdc-list/_list.scss
media/src/scss/ltdc-pane/_map-pane.scss
media/src/scss/ltdc-theme/_comm.scss

All the fixes listed in this ticket: https://columbiactl.atlassian.net/browse/LT-362

UI bug fixes Jira item LT-362

---

media/src/activity/activity-map-pane-panels.tsx
media/src/scss/ltdc-button/_button.scss

CSS fix for Return-to-Responses and Back-to-layername wrapping incorrectly

---

locustempus/main/serializers.py
locustempus/main/tests/test_viewsets.py

Fixes a bug where an image being removed from an event would not be
deleted.

LT-372 Image Update Bug

---

cypress/integration/activity.spec.js
cypress/integration/project-layers.spec.js
cypress/integration/project.spec.js
cypress/integration/workspace-roster-invite.spec.js
cypress/support/commands.js
locustempus/main/management/commands/integrationserver.py
locustempus/main/tests/factories.py
locustempus/templates/main/course_detail.html
media/src/activity/activity-map-pane-panels.tsx
media/src/activity/activity-map-pane.tsx
media/src/project-activity-components/layers/layer-set.tsx
media/src/project-activity-components/layers/layer.tsx
media/src/project-activity-components/panels/activity.tsx
media/src/project/project-map-pane-panels.tsx
media/src/project/project-map-pane.tsx

* abstract out faculty login into a command.
* add an additional student login command
* add additional project tests
* add a suite of project layer tests
* add a suite of activity tests that include role-based checks.

Project & Activity integration tests

---

cypress/integration/activity-response.spec.js
cypress/integration/activity.spec.js
cypress/integration/project-layers.spec.js
cypress/integration/project.spec.js
cypress/integration/workspace-roster-invite.spec.js
cypress/integration/workspace.spec.js
cypress/support/commands.js

just cleaning this up a little bit

integration tests: refactor the login

---

locustempus/main/permissions.py
locustempus/main/tests/test_viewsets.py
locustempus/main/viewsets.py

- Activity API Faculty Permissions
- Activity API Student Permissions
- Activity API Non-Course User Permissions
- Activity API Anon Permissions

activity api permissions

---

locustempus/templates/main/course_roster_invite.html

This commit adds back some needed class names to fix a regression with the
invite form.

Roster invite form bugfix

---

requirements.txt

Waiting for a fix with public-read acl

Rollback django-s3-sign

---

cypress/integration/activity-response.spec.js
locustempus/main/middleware.py
locustempus/settings_shared.py
locustempus/templates/admin/login.html
locustempus/templates/django_registration/registration_form.html
package-lock.json
requirements.txt

Upgrade django

---

media/src/activity/activity-map.tsx
media/src/project-activity-components/common.tsx
media/src/project/project-map.tsx

* Look for a location, have a popup with a link to open the event creation.
TODO: 
* Clean up the search input. Should clear.
* Figure out how to test

search feature interactions

---

cypress/e2e/events.cy.js
media/src/activity/activity-map.tsx
media/src/project-activity-components/layers/aggregated-layer-set.tsx
media/src/project-activity-components/panels/event-add-panel.tsx
media/src/project-activity-components/panels/event-edit-panel.tsx

* add in options for the time filter

filter options

---

locustempus/main/views.py
locustempus/templates/main/user_profile.html
locustempus/urls.py
media/src/scss/ltdc-pages/course_roster_invite_page.scss

* A very basic implementation of a profile page
* Gives the user the ability to add/change their first and last name
* Created because currently when a user is added in by uni, there isn't a name attached the user account

profile page

---

media/src/activity/activity-map.tsx
media/src/project/project-map.tsx

* link added to open the event panel when clicked. 
* wasn't sure how to style or if maybe it should be a btn? @zmustapha edit: made it a button

add a more link to popup

---

locustempus/settings_shared.py
requirements.txt

Reverts ccnmtl/locustempus#2606

Revert "revert the ccnmtl settings for now"

---

media/src/activity/activity-map.tsx
media/src/project/project-map.tsx

These changes will make it so the geocoder is aware of where a user is on a map and base search results on that. Will also increase the amount of search results

add proximity tracker

---

media/src/project-activity-components/layers/layer.tsx
media/src/project-activity-components/overflow-menu.tsx

I think this works better than the hamburger/bar icon for menu dropdown

Changed the icon for edit-menu dropdown to faEdit pencil

---

media/src/project-activity-components/layers/layer.tsx
media/src/scss/ltdc-list/_list-group.scss
media/src/scss/ltdc-theme/_comm.scss

* when a layer is untitled, show notice and turn text red

bring attention to untitled layers

---

cypress/e2e/activity-response.cy.js
media/src/activity/activity-map-pane-panels.tsx
media/src/activity/activity-map-pane.tsx
media/src/activity/activity-map.tsx
media/src/project-activity-components/common.tsx
media/src/project-activity-components/layers/aggregated-layer-set.tsx
media/src/project-activity-components/layers/layer-set.tsx
media/src/project-activity-components/layers/responseLayer.tsx
media/src/project/project-map-pane-panels.tsx

* redo the author responses view so that it most closely resembles a contributor's responses pane
* implement event date filtering 
**TODO:** 
* Right now the events are not collapsed but the specs specify a collapsible response box as opposed to response layers
* Clean it up

author date filter

---

.gitignore
Dockerfile
django.mk
docker-compose.yml
docker.mk
locustempus/settings_docker.py
requirements.txt

I can rebase it into one commit if you would prefer

New docker setup complete

---

requirements.txt

Reverts ccnmtl/locustempus#3146

Revert "Bump django-bootstrap4 from 24.1 to 24.2"

---

locustempus/settings_shared.py
locustempus/templates/403.html
locustempus/templates/404.html
locustempus/templates/base_design.html
locustempus/templates/main/lti_course_connect.txt

Reverts ccnmtl/locustempus#3676

Revert "Updated the contact email"
